@startuml
title Warm House Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

Person(User, "User", "A user of the warmhouse system")
Person(Admin, "Admin", "An admin (aka technician) mounts and connects new sensors to the system")

System(WarmHouseSystem, "Warm House System", "Heating control system")

System_Ext(SensorsApi, "Sensors API", "External API for receiving temperature from sensors")
System_Ext(HeatingApi, "Heating API", "External API for heating control")

Rel(User, WarmHouseSystem, "Authentication/Authorization")
Rel(User, WarmHouseSystem, "Views temperature")

Rel(Admin, WarmHouseSystem, "Authentication/Authorization")
Rel(Admin, WarmHouseSystem, "Manages sensors")

Rel(WarmHouseSystem, SensorsApi, "Receive temperature")

Rel(WarmHouseSystem, HeatingApi, "Controls heating")

@enduml