@startuml
title WarmHouse Container Diagram

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define SPRITES https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites
!include SPRITES/go.puml
!include SPRITES/postgresql.puml
!include SPRITES/nginx.puml
!include SPRITES/javascript.puml
!include SPRITES/kafka.puml

Person(User, "User", "A user of the warmhouse system")

Container_Boundary(WarmHouseBoundary, "WarmHouse System") {
  Container(WebApplication, "Users Web-Application", "HTML, JavaScript", "Web Application for users", $sprite="javascript")

  Container(UsersService, "Users Service", "Go", "Service for user's authentication and authorization", $sprite="go")
  ContainerDb(UsersDatabase, "Users Database", "PostgreSQL", "Stores user data, permissions and sessions", $sprite="postgresql")

  Container(DevicesService, "Devices Service", "Go", "Service for devices management", $sprite="go")
  ContainerDb(DevicesDatabase, "Devices Database", "PostgreSQL", "Stores devices data", $sprite="postgresql")

  Container(ScenarioService, "Scenario Service", "Go", "Service for managing/triggering/scheduling scenarios", $sprite="go")
  ContainerDb(ScenarioDatabase, "Scenario Database", "PostgreSQL", "Stores scenarios data", $sprite="postgresql")

  Container(TelemetryService, "Telemetry Service", "Go", "Service for managing/collecting telemetry", $sprite="go")
  Container(TelemetryStreamService, "Telemetry Stream Service", "Go", "Service collecting and publish telemetry from devices", $sprite="go")
  ContainerDb(TelemetryDatabase, "Telemetry Database", "PostgreSQL", "Stores telemetry data", $sprite="postgresql")


  Container(APIGateway, "API Gateway", "NGINX", "Proxy server", $sprite="nginx")
  ContainerQueue(MessageBroker, "Message Broker", "Apache Kafka Cluster", "Message bus for services communication", $sprite="kafka")
}

System_Ext(ExternalDevicesAPI, "External Devices API", "API for devices connected by the client")

'Web'
Rel(User, WebApplication, "Authentication/Authorization")
Rel(User, WebApplication, "Manages devices")
Rel(User, WebApplication, "Manages scenarios")

Rel(WebApplication, APIGateway, "Sends request", "HTTPS")

'Users'
Rel(APIGateway, UsersService, "Proxy request", "REST")
Rel(UsersService, UsersDatabase, "Reads/Writes users data")

'Telemetry'
Rel(APIGateway, TelemetryService, "Proxy request", "REST")
Rel(MessageBroker, TelemetryService,  "Reads telemetry data", "json", "topic: telemetry")
Rel(TelemetryService, TelemetryDatabase, "Reads/writes telemetry data", "json", "topic: telemetry")

Rel(ExternalDevicesAPI, TelemetryStreamService, "Publishes devices telemetry", "open protocol")
Rel(TelemetryStreamService, MessageBroker, "Publishes devices telemetry", "json", "topic: telemetry")

'Devices'
Rel(APIGateway, DevicesService, "Proxy request", "REST")
Rel(MessageBroker, DevicesService,  "Reads devices data", "json", "topic: devices")
Rel(DevicesService, MessageBroker, "Publishes devices data", "json", "topic: devices")
Rel(DevicesService, DevicesDatabase, "Reads/writes devices data")

'Scenario
Rel(APIGateway, ScenarioService, "Proxy request", "REST")
Rel(MessageBroker, ScenarioService,  "Reads devices data", "json", "topic: scenarios")
Rel(ScenarioService, MessageBroker, "Publishes scensarios data", "json", "topic: scenarios")
Rel(ScenarioService, ScenarioDatabase, "Reads/writes scenarios data")

@enduml
