@startuml
title WarmHouse Devices Sub‑system (Component)

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary(WarmHouseBoundary, "WarmHouse System") {
    Container(DevicesService, "Devices Service", "Go", $sprite="go")
    Container(APIGateway, "API Gateway", "NGINX", "Proxy server", $sprite="nginx")
    ContainerQueue(MessageBroker, "Message Broker", "Apache Kafka Cluster", "Message bus for services communication", $sprite="kafka")
    ContainerDb(DevicesDatabase, "Devices Database", "PostgreSQL", "Stores devices data", $sprite="postgresql")
}

Container(DevicesService, "Devices Service") {
  Component(Consumer, "Devices Consumer", "Consumes device data messages")
  Component(ConsumerServiceLayer, "Consumer Service Layer", "Business logic")
  Component(Controller, "Devices Controller", "Handles devices operations")
  Component(ControllerServiceLayer, "Controller Service Layer", "Business logic")
  Component(RepositoryLayer, "Repository Layer", "Data access")
}

Rel(APIGateway, Controller, "Calls API")

Rel(Controller, ControllerServiceLayer, "Calls business logic")
Rel_U(ControllerServiceLayer, MessageBroker, "Publishes devices data")
Rel(ControllerServiceLayer, RepositoryLayer, "Reads data")

Rel(Consumer, ConsumerServiceLayer, "Calls business logic")
Rel_U(Consumer, MessageBroker, "Reads devices data")
Rel(ConsumerServiceLayer, RepositoryLayer, "Reads/Writes data")

Rel(RepositoryLayer, DevicesDatabase, "Reads/Writes data")



@enduml
