@startuml
title WarmHouse Container Diagram

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(User, "User", "A user of the warmhouse system")
Person(Admin, "Admin", "An admin (aka technician) mounts and connects new sensors to the system")

Container_Boundary(WarmHouseBoundary, "Warm House System") {
  Container(WebApplication, "Web-Application", "HTML, JavaScript", "Web Application for users")

  Container(UsersService, "Users Service", "Go", "Service for user's authentication and authorization")
  Container(SensorsService, "Sensors Service", "Go", "Service for sensors management")
  Container(HeatingService, "Heating Service", "Go", "Service for viewing temperature")

  Container(Database, "Database", "PostgreSQL", "Stores temperature, sensors and users data")
}

System_Ext(HeatingControlApi, "Heating Control API", "External API for heating control")
System_Ext(TemperatureSensorApi, "Temperature Data API", "External API for receiving temperature from sensors")

Rel(Admin, WebApplication, "Authentication\nAuthorization")
Rel(Admin, WebApplication, "Create/Read/\nUpdate/Delete sensors")

Rel(User, WebApplication, "Authentication\nAuthorization")
Rel(User, WebApplication, "View\ntemperature")
Rel(User, WebApplication, "Enable/disable\nheating")

Rel_D(WebApplication, SensorsService, "Enable/disable\nheating")
Rel_R(WebApplication, HeatingService, "View\ntemperature")
Rel_L(WebApplication, UsersService, "Authentication\nAuthorization")

Rel(HeatingService, SensorsService, "Get\nsensors")
Rel(HeatingService, Database, "Read/Write\nheating data")
Rel_R(HeatingService, HeatingControlApi, "Enable/disable\nheating")
Rel_D(HeatingService, TemperatureSensorApi, "Receive temperature\nfrom sensor")

Rel(UsersService, Database, "Read/Write\nusers data")

Rel_D(SensorsService, Database, "Read/Write\nsensors data")

@enduml