@startuml
title Warm House Context Diagram

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(User, "User", "A user of the warmhouse system")
Person(Admin, "Admin", "An admin (aka technician) mounts and connects new sensors to the system")

System(WarmHouseSystem, "Warm House System", "Heating control system")

System_Ext(HeatingControlApi, "Heating Control API", "External API for heating control")
System_Ext(TemperatureSensorApi, "Temperature Sensor API", "External API for receiving temperature from sensors")

Rel(User, WarmHouseSystem, "Authentication/Authorization")
Rel(User, WarmHouseSystem, "Views temperature")

Rel(Admin, WarmHouseSystem, "Authentication/Authorization")
Rel(Admin, WarmHouseSystem, "Manages sensors")

Rel(WarmHouseSystem, TemperatureSensorApi, "Receive temperature")

Rel(WarmHouseSystem, HeatingControlApi, "Controls heating")

@enduml